### ISSUE TITLE
Error when using "№" as table row data in table

### ISSUE THREAD

**Issue by shakhrillodev** [siaikin/vue-to-print#13]
Here is my code. And when I call handlePrint method. It is not showing print window.
```
        <thead>
        <tr>
          <td>№</td>
          <td>Workplace</td>
          <td>Last Name</td>
          <td>First Name</td>
          <td>Total score</td>
          <td>End Date</td>
          <td>Duration</td>
        </tr>
        </thead>
```

**Comment by siaikin** [comment]
This is a bit confusing 🤔️, I added the stackblitz example and tested the html snippet you provided, and everything worked fine.

I've shown [stackblitz example link] (https://github.com/siaikin/vue-to-print?tab=readme-ov-file#example) in the readme file, please use this link to make an example showing your problem.

**Comment by shakhrillodev** [comment]
I do not know how it happened. But after some time I tried to refresh it the next day and it worked fine. Maybe it was because of some cache problems. Anyway thanks. Good luck with the project.

**Comment by siaikin** [comment]
Aha！Web is magic😵‍💫
发自我的 iPhone

在 2024年10月31日，17:43，Shaxrillo Nusratov ***@***.***> 写道：

﻿

I do not know how it happened. But after some time I tried to refresh it the next day and it worked fine. Maybe it was because of some cache problems. Anyway thanks. Good luck with the project.
