### ISSUE TITLE
print: (target) => {} NOT WORKING

### ISSUE THREAD

**Issue by bright-coder** [siaikin/vue-to-print#16]
const { handlePrint } = useVueToPrint({
  content: () => containerRef.value as HTMLElement,
  onBeforePrint: () => {
    printState.value = 'printing'
  },
  print: (target: HTMLIFrameElement) => {
    if (!target.contentWindow) return Promise.resolve()

    const data = target.contentWindow.document.documentElement.outerHTML

    const blob = new Blob([data], { type: 'text/html;charset=UTF-8' })
    const url = URL.createObjectURL(blob)
    return window.mainApi.send('print-delivery-order-reciept', url)
  }
})

NOT WORKING ****** target is undefined *******

**Comment by siaikin** [comment]
@bright-coder hi. Thank you very much for your feedback, please try the latest version.
