### ISSUE TITLE
[BUG]:  `documentTitle` options does not work on Chrome Browser

### ISSUE THREAD

**Issue by Us3r-gitHub** [siaikin/vue-to-print#20]
**Describe the bug**
In the playground example, the `documentTitle` options is defined, but when I try to print and save it, the filename is empty.

**Expected behavior**
Shouldn't the filename be populated with the `documentTitle` value?

**Comment by siaikin** [comment]
You're right, but browsers always have some weird behavior.
Please see the first item of https://github.com/MatthewHerbst/react-to-print?tab=readme-ov-file#common-pitfalls.

CodeSandbox previews the playground run in an iframe, so the title of the printed document is the title of the main document.

**Comment by Us3r-gitHub** [comment]
How can we tell if we've implemented an iframe? I tested it locally, and it seems the same.

How can we avoid implementing an iframe?

**Comment by siaikin** [comment]
I tested in local mode and both Chrome and Firefox worked fine. I use Macos.

Please provide your operating environment, system and browser version.

You can also test it by visiting the online documentation, https://vue-to-print.netlify.app/guide/basic-usage.html which has an example file name called `AwesomeFileName`.

**Comment by Us3r-gitHub** [comment]
It worked in Firefox, but not in Chrome (or Brave).

My environment:

- Windows 11
- Chrome (131.0.6778.86)
- Brave (1.73.91)

**Comment by siaikin** [comment]
I'm testing on Windows 10 and there are two scenarios.

1. Select the 'Microsoft Print to PDF' target printer in the print preview box and click Save, the file selector will pop up, and the Chinese part name column is empty.
2. Select 'Save as PDF' in the print preview box and click Save, the file selector will pop up with the Chinese name column '${documentTitle}.pdf', which is expected.

@Us3r-gitHub: Is this a situation you're in? If so, this won't be the responsibility of 'vue-to-print' (this should be a specific behavior for 'Microsoft Print to PDF'), and if not, I'll troubleshoot further.

> 我在 Windows 10 上测试，有两种情况.
> 
> 1. 在打印预览框中选择 `Microsoft Print to PDF` 目标打印机然后点击保存，会弹出文件选择器，其中文件名一栏是空的。
> 2. 在打印预览框中选择 `Save as PDF` 目标打印机然后点击保存，会弹出文件选择器，其中文件名一栏是 `${documentTitle}.pdf`，这是符合预期的。
> 
> @Us3r-gitHub 这是你碰到的情况吗？如果是，这将不是 `vue-to-print` 负责的范围（这应该是`Microsoft Print to PDF`的特定行为）,如果不是，我将进一步排查问题。

**Comment by Us3r-gitHub** [comment]
Thanks for your help!

I’m not sure what the scenario is, but I recorded a video using Windows Recorder and want to share it. However, when I replay the video, the pop-up print window doesn’t appear in the recording :(.

https://github.com/user-attachments/assets/d4c974af-07da-465d-a38c-d00a5031c97e

I think it’s a browser issue because it works on Firefox but not on Chrome, as mentioned in your [comment ](https://github.com/siaikin/vue-to-print/issues/18#issuecomment-2510516010)

**Comment by siaikin** [comment]
check this 
![image](https://github.com/user-attachments/assets/8ca69e75-edae-4089-a6d4-fca0103fa509)

change to `Save as PDF`

**Comment by Us3r-gitHub** [comment]
> change to `Save as PDF`

Thanks, that works! Just a small change and it works properly now.
You're a pro!
