### ISSUE TITLE
[BUG]:  Cannot print ShadCN Vue Tabs component

### ISSUE THREAD

**Issue by Us3r-gitHub** [siaikin/vue-to-print#21]
**Describe the bug**  
When attempting to print a page that contains the ShadCN Vue Tabs component, I receive an error:  
`To print a functional component ensure it is wrapped with React.forwardRef, and ensure the forwarded ref is used. See the README for an example: https://github.com/gregnb/react-to-print#examples`.

**To Reproduce**  
I have created a repository to reproduce this issue: [GitHub repo](https://github.com/Us3r-gitHub/Playground-Nuxt/tree/vue_to_print-dynamic).

**Expected behavior**  
I expect the page, including the ShadCN Vue Tabs component, to print without any errors.

**Screenshots**  

https://github.com/user-attachments/assets/43b32e72-d4d7-450c-9e1b-c06a2b339629

**Comment by siaikin** [comment]
You define the ref in v-for, which will cause the value of componentRef to become an array. [template reference in v-for] (https://cn.vuejs.org/guide/essentials/template-refs.html#refs-inside-v-for)。 This will make vue-to-print not know which element should be printed.

You can always select the first element in the array, like the following.
```js
// VueToPrint
const componentRef = ref();
const { handlePrint } = useVueToPrint({
  content: computed(() => componentRef.value[0]),
  documentTitle: currentTab,
  removeAfterPrint: true,
});
```

**Comment by Us3r-gitHub** [comment]
Thanks for your quick response! It works for now, and no errors occur.

However, when I switch to the second tab (`password`) and click the print button, the print preview is blank.

**Comment by Us3r-gitHub** [comment]
I tested a workaround and observed the following results:

<details>
  <summary>Works well when declaring ref in the correct component</summary>

  ```html
  <TabsContent v-for="tab in tabs" :key="tab.key" :value="tab.key">
    <BaseTabContent :type="currentTab" ref="componentRef" />
  </TabsContent>
  ```
</details>

<details>
  <summary>Results in a blank preview for tabs other than the first when declaring ref in v-for</summary>
  
  ```html
  <TabsContent v-for="tab in tabs" :key="tab.key" :value="tab.key" ref="componentRef">
    <BaseTabContent :type="currentTab" />
  </TabsContent>
  ```
</details>

Thank you so much for your help! I really appreciate it.
