### ISSUE TITLE
DOMException: Failed to set the 'adoptedStyleSheets' property on 'ShadowRoot': Sharing constructed stylesheets in multiple documents is not allowed

### ISSUE THREAD

**Issue by NeluQi** [siaikin/vue-to-print#4]
DOMException: Failed to set the 'adoptedStyleSheets' property on 'ShadowRoot': Sharing constructed stylesheets in multiple documents is not allowed

![image](https://github.com/siaikin/vue-to-print/assets/16963395/2800eeb7-b408-4573-8211-bedf85ab1195)

i am use Ionic + primevue 

Ionic use ShadowRoot

pls fix

**Comment by siaikin** [comment]
Great question, I haven't worked with Web Components related stuff before. To quickly locate the issue, can you provide a reproducible example of the problem?

**Comment by NeluQi** [comment]
![image](https://github.com/siaikin/vue-to-print/assets/16963395/569c332e-b3d4-4b95-9392-8b9bad0bd8bf)

npm i
npm run serve

click "Print using a Component"
see console 


[bug-ionic-modal-master.zip](https://github.com/siaikin/vue-to-print/files/12483792/bug-ionic-modal-master.zip)

**Comment by siaikin** [comment]
Hi, I have released version `v1.1.0-alpha.1` to support DOM elements created via Web Components. I have tested it with some Ionic components [docs](https://deploy-preview-5--vue-to-print.netlify.app/guide/basic-usage.html#print-shadow-dom-using-hook) and it works fine, but it's not perfect yet, so I would appreciate it if you could use it and give me feedback.

**Comment by siaikin** [comment]
Any other questions? I will close this issue and release a new version.
