### ISSUE TITLE
[Bug] Printing with the component does not work

### ISSUE THREAD

**Issue by grantorin** [siaikin/vue-to-print#9]
**Printing with the component does not work**
Printing with the component does not work even on the documentation page

**To Reproduce**
1. Go to '[print-using-a-component](https://vue-to-print.netlify.app/guide/basic-usage.html#print-using-a-component)'
2. Click on 'Print'
3. See error in console

**Screenshots**
![image](https://github.com/user-attachments/assets/4c87358a-71a7-44e5-bc9b-e063c33e24b9)

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Browser [chrome]
 - Version [128.0.6613.120]

**Comment by siaikin** [comment]
Thank you so much for reporting this bug.

This is an issue with the documentation sample code, and I'll fix it right away.
